class DesignerGroup < Cask
  depends_on cask: 'font-actor'
  depends_on cask: 'font-aleo'
  depends_on cask: 'font-arvo'
  depends_on cask: 'font-code'
  depends_on cask: 'font-comic-neue'
  depends_on cask: 'font-devicons'
  depends_on cask: 'font-fira-sans'
  depends_on cask: 'font-fontawesome'
  depends_on cask: 'font-lato'
  depends_on cask: 'font-open-iconic'
  depends_on cask: 'font-roboto'
  depends_on cask: 'font-roboto-slab'
  depends_on cask: 'font-source-code-pro'
  depends_on cask: 'font-source-sans-pro'
  depends_on cask: 'font-source-serif-pro'
  depends_on cask: 'font-yanone-kaffeesatz'
end
